-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MAX_FAV
ON MAX_FAV.MF = REST_INFO.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC