-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT HOURS.HOUR AS HOUR, IFNULL(COUNT, 0) AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR) AS COUNTS
    RIGHT JOIN HOURS ON COUNTS.HOUR = HOURS.HOUR
ORDER BY HOUR